services:
  ministack:
    image: ministackorg/ministack
    container_name: finflow-ministack
    ports:
      - "4566:4566"
    restart: unless-stopped

  aws-init:
    image: amazon/aws-cli
    container_name: finflow-aws-init
    depends_on:
      - ministack
    env_file:
      - .env
    entrypoint: ["sh", "-c"]
    command: >
      "aws configure set aws_access_key_id $$AWS_ACCESS_KEY_ID &&
       aws configure set aws_secret_access_key $$AWS_SECRET_ACCESS_KEY &&
       aws configure set region $$AWS_DEFAULT_REGION &&
       aws configure set output json &&
       echo 'AWS CLI configured for Ministack'"
    volumes:
      - ${USERPROFILE}/.aws:/root/.aws
    
  terraform-init:
    image: hashicorp/terraform:1.15
    container_name: finflow-terraform-init
    working_dir: /workspace
    volumes:
      - .:/workspace
    depends_on:
      ministack:
        condition: service_healthy
    entrypoint: sh
    command: -c "cd terraform/environments/dev && terraform init && terraform apply -auto-approve"

volumes:
  ministack_data: