services:
  ministack:
    image: ministackorg/ministack:full
    container_name: finflow-ministack
    ports:
      - "4566:4566"
    restart: unless-stopped
    environment:
      - S3_PERSIST=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  aws-init:
    image: amazon/aws-cli
    container_name: finflow-aws-init
    depends_on:
      - ministack
    env_file:
      - .env
    entrypoint: ["sh", "-c"]
    command: >
      "aws configure set aws_access_key_id $$AWS_ACCESS_KEY_ID &&
       aws configure set aws_secret_access_key $$AWS_SECRET_ACCESS_KEY &&
       aws configure set region $$AWS_DEFAULT_REGION &&
       aws configure set output json &&
       echo 'AWS CLI configured for Ministack'"
    volumes:
      - ${USERPROFILE}/.aws:/root/.aws
    
  terraform-init:
    image: hashicorp/terraform:1.15
    container_name: finflow-terraform-init
    working_dir: /workspace
    volumes:
      - .:/workspace
    depends_on:
      ministack:
        condition: service_healthy
    entrypoint: sh
    command: -c "cd terraform/environments/dev && terraform init && terraform apply -auto-approve"
  
  stackport:
    image: davireis/stackport
    container_name: finflow-stackport
    ports:
      - "8080:8080"
    environment:
      - AWS_ENDPOINT_URL=http://ministack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=ap-southeast-1
    depends_on:
      - ministack
  
  pipeline-trigger:
    image: amazon/aws-cli
    container_name: finflow-pipeline-trigger
    depends_on:
      terraform-init:
        condition: service_completed_successfully
    env_file:
      - .env
    entrypoint: ["sh", "-c"]
    command: >
      "aws stepfunctions start-execution
       --endpoint-url=http://ministack:4566
       --state-machine-arn arn:aws:states:$$AWS_DEFAULT_REGION:000000000000:stateMachine:finflow-etl-pipeline"

volumes:
  ministack_data: